# Exported from Render on 2024-07-26T09:14:31Z
services:
- type: web
  name: ChatterBox
  runtime: python
  repo: https://github.com/iamyash2601/ChatterBox
  plan: free
  envVars:
  - key: COHERE_API_KEY
    sync: false
  - key: PINECONE_API_KEY
    sync: false
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app:app
version: "1"
